scoring-base: 'http://crawl.kelbi.org/morgue-test'

sources:
  - name: cko
    base: http://crawl.kelbi.org/crawl
    logfiles:
      - meta/0.18/logfile
      - meta/0.21/logfile
      - meta/0.22/logfile
      - meta/git/logfile
      - meta/hellcrawl/logfile
      - meta/bcrawl/logfile
    milestones:
      - meta/0.18/milestones
      - meta/0.21/milestones
      - meta/0.22/milestones
      - meta/git/milestones
      - meta/hellcrawl/milestones
      - meta/bcrawl/milestones
    morgues:
      - http://crawl.kelbi.org/crawl/morgue

